apiVersion: v1
kind: Service
metadata:
  name: solar-system
spec:
  type: NodePort
  selector:
    app: solar-system
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32463   # fixed port for testing